/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"

bool_t
xdr_mo (XDR *xdrs, mo *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->m))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_min_max (XDR *xdrs, min_max *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ay (XDR *xdrs, ay *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->b.b_val, (u_int *) &objp->b.b_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->res.res_val, (u_int *) &objp->res.res_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}
