/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
find_m_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		mo find_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FIND:
		_xdr_argument = (xdrproc_t) xdr_mo;
		_xdr_result = (xdrproc_t) xdr_mo;
		local = (char *(*)(char *, struct svc_req *)) find_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
find_min_max_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		min_max find_mn_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FIND_MN:
		_xdr_argument = (xdrproc_t) xdr_min_max;
		_xdr_result = (xdrproc_t) xdr_min_max;
		local = (char *(*)(char *, struct svc_req *)) find_mn_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calc_ay_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ay find_ay_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case FIND_AY:
		_xdr_argument = (xdrproc_t) xdr_ay;
		_xdr_result = (xdrproc_t) xdr_ay;
		local = (char *(*)(char *, struct svc_req *)) find_ay_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FIND_M, FIND_VERS);
	pmap_unset (FIND_MIN_MAX, MIN_MAX_VERS);
	pmap_unset (CALC_AY, AY_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FIND_M, FIND_VERS, find_m_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FIND_M, FIND_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, FIND_MIN_MAX, MIN_MAX_VERS, find_min_max_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FIND_MIN_MAX, MIN_MAX_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALC_AY, AY_VERS, calc_ay_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALC_AY, AY_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FIND_M, FIND_VERS, find_m_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FIND_M, FIND_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, FIND_MIN_MAX, MIN_MAX_VERS, find_min_max_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FIND_MIN_MAX, MIN_MAX_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALC_AY, AY_VERS, calc_ay_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALC_AY, AY_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
