/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
/* ΒΙΚΤΩΡ ΡΟΜΑΝΙΟΥΚ 713242017024 ΕΡΓ1 */
#include "ask1.h"

mo *find_1_svc(mo *argp, struct svc_req *rqstp)
{
	printf("Starting Operation MO! \n");
	static mo result;
	result.m = 0;
	result.b.b_len = argp->b.b_len;
	result.b.b_val = (int *)malloc(result.b.b_len * sizeof(int));
	for (int i = 0; i < result.b.b_len; i++)
	{
		result.b.b_val[i] = argp->b.b_val[i];
		result.m = result.m + result.b.b_val[i];
	}
	result.m = result.m / (float)result.b.b_len;

	return &result;
}

min_max *
find_mn_1_svc(min_max *argp, struct svc_req *rqstp)
{
	printf("Starting Operation Min_MAX! \n");
	static min_max result;

	result.b.b_len = argp->b.b_len;
	result.b.b_val = (int *)malloc(result.b.b_len * sizeof(int));
	result.max = 0;
	result.min = 9999999;
	for (int i = 0; i < result.b.b_len; i++)
	{
		result.b.b_val[i] = argp->b.b_val[i];
		if (result.b.b_val[i] <= result.min)
		{
			result.min = result.b.b_val[i];
		}
		if (result.max <= result.b.b_val[i])
		{
			result.max = result.b.b_val[i];
		}
	}

	/*
	 * insert server code here
	 */
	printf("RETURNING RESULT\n");
	return &result;
}

ay *find_ay_1_svc(ay *argp, struct svc_req *rqstp)
{
	printf("Starting Operation AY\n");
	static ay result;
	result.res.res_len = argp->b.b_len;
	result.res.res_val = (float *)malloc(result.b.b_len * sizeof(float));
	for (int i = 0; i < result.res.res_len; i++)
	{
		result.res.res_val[i] = argp->b.b_val[i] * argp->a;
	}

	/*
	 * insert server code here
	 */

	return &result;
}
