/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ask1.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

mo *
find_1(mo *argp, CLIENT *clnt)
{
	static mo clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FIND,
		(xdrproc_t) xdr_mo, (caddr_t) argp,
		(xdrproc_t) xdr_mo, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

min_max *
find_mn_1(min_max *argp, CLIENT *clnt)
{
	static min_max clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FIND_MN,
		(xdrproc_t) xdr_min_max, (caddr_t) argp,
		(xdrproc_t) xdr_min_max, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ay *
find_ay_1(ay *argp, CLIENT *clnt)
{
	static ay clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FIND_AY,
		(xdrproc_t) xdr_ay, (caddr_t) argp,
		(xdrproc_t) xdr_ay, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
